FROM %%DOCKER_REPO%%:%%BASE_IMAGE_TAG%%

# Install packages
RUN yum -y install \
  python-pip git gcc python-devel \
  dh-autoreconf curl-devel expat-devel gettext-devel openssl-devel perl-devel zlib-devel wget\
 && yum clean all

RUN wget https://www.kernel.org/pub/software/scm/git/git-%%GIT_VERSION%%.tar.gz \
         -O /tmp/git-%%GIT_VERSION%%.tar.gz \
 && cd /tmp/ \
 && tar xzf git-%%GIT_VERSION%%.tar.gz \
 && cd /tmp/git-%%GIT_VERSION%% \
 && make prefix=/usr/local/git all \
 && make prefix=/usr/local/git install \
 && yum -y remove git \
 && ln -s /usr/local/git/bin/git /usr/bin/git \
 && rm -rf /tmp/git-%%GIT_VERSION%%.tar.gz /tmp/git-%%GIT_VERSION%%

RUN yum -y reinstall glibc-common \
 && localedef -i en_US -f UTF-8 en_US.UTF-8 \
 && localedef -i en_GB -f UTF-8 en_GB.UTF-8 \
 && yum clean all

RUN pip install --upgrade pip docker-py \
 && pip install git+git://github.com/ansible/ansible.git@%%ANSIBLE_VERSION%%
